const vehicles = [
  {
    name: "Renault Trafic 1.6 dCi ENERGY 29 Sport Crew Van LWB Euro 5 (s/s) 5dr",
    make: "Renault",
    model: "Trafic",
    price: 10000,
    description: `*** MOT APRIL 2026 *** HUGE SPEC *** BODYWORK AROUND FRONT BUMPER TATTY * ENGINE LIGHT ON * VAN HAS HAD NEW SET OF CLOCKS AND SHOWS 85K *** BARGAIN PRICE *** ** TRADE SALE WITH NO WARRANTY ** 

    This Is A Part Exchange We Have Taken In But Does Not Meet Our Standards For Retail * Being Sold With No Warranty Whatsoever As A Trade Sale * You Are Welcome To View And Drive The Vehicle Before You Pay * Please Make Sure That You Check The MOT Expiry Date As Vehicles Without An MOT Will Need To Be Moved On A Car Transporter And Not Driven Away * We Are Located Just 30 Seconds From Junction 10 Off The M56, Behind The Spire Hospital, Its Really Easy To Get To Us! Warrington Car & Van Sales Are A Trusted Local Family Run Business With Over 25 Years Motor Trade Experience. We Open 8:45am to 5:30pm During The Week And 9am To 4pm On Saturday***** Call Today *****`,
    image: "images/van-pic1.jpg",
    year: 2015,
    mileage: 125000,
    fuelType: "Diesel",
    gearbox: "Manual",
    engineSize: "1.6L",
    color: "Grey",
    seats: 6,
    emissions: `160 g/km`,
    horsepower: "118 BHP",
    milesPerGallon: "46.3 MPG",
    euroStatus: "Euro 5",
    bodyType: "Combi Van",
    wheelbase: "LWB",
    id: 0,
    topSpeed: "107 mph",
    zeroToSixty: "12 secs",
    power: "118 bhp",
    height: "1,971mm",
    length: "5,399mm",
    width: "2,283mm",
    extraUrban: "0 mpg",
    urban: "0 mpg",
    imageSlides: [
      "images/van-pic1.jpg",
      "images/van-pic2.jpg",
      "images/van-pic3.jpg",
      "images/van-pic4.jpg",
      "images/van-pic5.jpg",
    ],
  },

  {
    name: `Citroen Berlingo 1.6 HDi 625 Enterprise Panel Van 5dr L1`,
    make: "Citroen",
    model: "Berlingo",
    price: 5000,
    description: `For Sale: 2013 Citroen Berlingo Panel Van (63 Plate)
    - 73,000 miles
    - Full Service history
    - Finished in white
    - Equipped with Bluetooth, air conditioning, and rear parking sensors
    - Fitted with a roof rack for added practicality

    This well-maintained and reliable van is in excellent condition and offers a tidy, professional appearance. With low mileage for its age, it drives smoothly and is ready for immediate use, making it ideal for both business and personal applications. Practical, dependable, and versatile, this Citroen Berlingo is a great choice for anyone in need of a functional and efficient vehicle.  
    `,
    image: "images/citroenBerlingoPanelVan.JPG",
    year: 2013,
    mileage: 73000,
    fuelType: "Diesel",
    gearbox: "Manual",
    engineSize: "1.6L",
    color: "White",
    seats: 3,
    emissions: `133 g/km`,
    horsepower: "75 BHP",
    milesPerGallon: "55.4 MPG",
    euroStatus: "Euro 5",
    bodyType: "Panel Van",
    wheelbase: "SWB",
    id: 1,
    topSpeed: "92 mph",
    zeroToSixty: "16.6 secs",
    power: "75 bhp",
    height: "1,812mm",
    length: "4,380mm",
    width: "1,810mm",
    extraUrban: "0 mpg",
    urban: "0 mpg",
    imageSlides: [
      "images/citroenBerlingoPanelVan.jpg",
      "images/citroenBerlingoPanelVan1.jpg",
      "images/citroenBerlingoPanelVan2.jpg",
      "images/citroenBerlingoPanelVan3.jpg",
      "images/citroenBerlingoPanelVan4.jpg",
      "images/citroenBerlingoPanelVan5.jpg",
      "images/citroenBerlingoPanelVan6.jpg",
      "images/citroenBerlingoPanelVan7.jpg",
      "images/citroenBerlingoPanelVan8.jpg",
      "images/citroenBerlingoPanelVan9.jpg",
      "images/citroenBerlingoPanelVan10.jpg",
      "images/citroenBerlingoPanelVan11.jpg",
    ],
  },

  {
    name: "Volkswagen Caddy 2.0 TDI C20 BlueMotion Tech Startline SWB Euro 6 (s/s) 5dr",
    make: "Volkswagen",
    model: "Caddy",
    price: 3750,
    description: `This Volkswagen Caddy is a fantastic example, having had only one owner since new.  This 2016 registered 2.0 TDI C20 BlueMotion Tech Startline SWB Euro 6 (s/s) 5dr is a practical and efficient choice, powered by a 2.0 litre diesel engine.  The Startline trim level offers essential features, including Bluetooth connectivity for your convenience.

    You'll appreciate the impressive fuel economy of this Caddy, achieving an outstanding 61 miles per gallon, which is significantly better than many other vehicles in its class. Furthermore, its Euro 6 emission rating and low CO2 emissions contribute to lower running costs and environmental impact. This vehicle also benefits from being in a low insurance group, making it an economical option for many drivers.`,
    image: "images/volkswagen-caddy1.jpg",
    year: 2016,
    mileage: 114000,
    fuelType: "Diesel",
    gearbox: "Manual",
    engineSize: "2.0L",
    color: "White",
    seats: 2,
    emissions: `120 g/km`,
    horsepower: "101 BHP",
    milesPerGallon: "61.4 MPG",
    euroStatus: "Euro 6",
    bodyType: "Panel Van",
    wheelbase: "SWB",
    id: 2,
    topSpeed: "107 mph",
    zeroToSixty: "12 secs",
    power: "118 bhp",
    height: "1,823mm",
    length: "4,408mm",
    width: "2,065mm",
    extraUrban: "0 mpg",
    urban: "0 mpg",
    imageSlides: [
      "images/volkswagen-caddy1.jpg",
      "images/volkswagen-caddy.jpg",
      "images/volkswagen-caddy2.jpg",
      "images/volkswagen-caddy3.jpg",
      "images/volkswagen-caddy4.jpg",
      "images/volkswagen-caddy5.jpg",
    ],
  },

  {
    name: "Peugeot Partner 1.5 BlueHDi 1000 Premium Standard Panel Van 5dr SWB Euro 6",
    make: "Peugeot",
    model: "Partner",
    price: 10490,
    description: `The Peugeot Partner 1.5 BlueHDi 1000 Professional Premium is a smart and reliable Euro 6 panel van designed for everyday business use. With its efficient 100 bhp diesel engine, smooth manual transmission, and short wheelbase design, it delivers a great balance of power, economy, and manoeuvrability. The Professional Premium trim adds extra comfort and convenience, making it a practical choice for both city driving and longer journeys.`,
    image: "images/peugeot.jpg",
    year: 2021,
    mileage: 49991,
    fuelType: "Diesel",
    gearbox: "Manual",
    engineSize: "1.5L",
    color: "Grey",
    seats: 3,
    emissions: `144 g/km`,
    horsepower: "100 BHP",
    milesPerGallon: "55.7 MPG",
    euroStatus: "Euro 6",
    bodyType: "Panel Van",
    wheelbase: "SWB",
    id: 3,
    topSpeed: "102 mph",
    zeroToSixty: "11.5 secs",
    power: "100 bhp",
    height: "1,840mm",
    length: "4,403mm",
    width: "2,107mm",
    extraUrban: "0 mpg",
    urban: "0 mpg",
    imageSlides: [
      "images/peugeot.jpg",
      "images/peugeot1.jpg",
      "images/peugeot2.jpg",
      "images/peugeot3.jpg",
      "images/peugeot4.jpg",
      "images/peugeot5.jpg",
    ],
  },

  {
    name: "Peugeot Boxer 2.2 BlueHDi 335 Professional L3 H2 Euro 6 (s/s) 5dr",
    price: 6950,
    make: "Peugeot",
    model: "Boxer",
    description: `The Peugeot Boxer 2.2 BlueHDi 335 Professional L3 H2 is a versatile large panel van built to handle demanding workloads with ease. Powered by a Euro 6 BlueHDi diesel engine and paired with stop/start efficiency, it delivers strong performance with reduced emissions. The long wheelbase (L3) and high roof (H2) design provide excellent load capacity, while the Professional trim adds comfort, connectivity, and practical features to support your business day after day.`,
    image: "images/peugeot-boxer.jpg",
    year: 2020,
    mileage: 122123,
    fuelType: "Diesel",
    gearbox: "Manual",
    engineSize: "2.2L",
    color: "White",
    seats: 3,
    emissions: `162 g/km`,
    horsepower: "138 BHP",
    milesPerGallon: "34.3 MPG",
    euroStatus: "Euro 6",
    bodyType: "Panel Van",
    wheelbase: "LWB",
    id: 4,
    topSpeed: "1118 mph",
    zeroToSixty: "12 secs",
    power: "138 bhp",
    height: "2,522mm",
    length: "5,998mm",
    width: "2,050mm",
    extraUrban: "0 mpg",
    urban: "0 mpg",
    imageSlides: [
      "images/peugeot-boxer.jpg",
      "images/peugeot-boxer1.jpg",
      "images/peugeot-boxer2.jpg",
      "images/peugeot-boxer3.jpg",
      "images/peugeot-boxer4.jpg",
      "images/peugeot-boxer5.jpg",
      "images/peugeot-boxer6.jpg",
    ],
  },

  {
    name: "Ford Transit Connect 1.5 Transit Connect 200 Trend",
    price: 8990,
    make: "Ford",
    model: "Transit Connect",
    description: `The Ford Transit Connect 1.5 200 Trend is a compact and efficient panel van designed to make light work of daily business needs. Powered by Ford’s reliable 1.5-litre diesel engine, it offers a strong blend of performance and fuel economy, making it ideal for city driving and longer runs alike. With its practical load space, easy access, and well-equipped Trend trim, it delivers comfort, connectivity, and smart features to keep your business moving smoothly.`,
    image: "images/ford-connect.jpg",
    year: 2017,
    mileage: 72589,
    fuelType: "Diesel",
    gearbox: "Manual",
    engineSize: "1.5L",
    color: "Blue",
    seats: 3,
    emissions: `119 g/km`,
    horsepower: "118 BHP",
    milesPerGallon: "61 MPG",
    euroStatus: "Euro 6",
    bodyType: "Panel Van",
    wheelbase: "SWB",
    id: 5,
    topSpeed: "107 mph",
    zeroToSixty: "12 secs",
    power: "118 bhp",
    height: "1,861mm",
    length: "4,418mm",
    width: "1,835mm",
    extraUrban: "0 mpg",
    urban: "0 mpg",
    imageSlides: [
      "images/ford-connect.jpg",
      "images/ford-connect1.jpg",
      "images/ford-connect2.jpg",
      "images/ford-connect3.jpg",
      "images/ford-connect4.jpg",
      "images/ford-connect5.jpg",
    ],
  },

  {
    name: "Ford Transit Custom 2.0 TDCi 310 L1 H1 5dr",
    make: "Ford",
    model: "Transit Custom",
    price: 6800,
    description: `The Ford Transit Custom 2.0 TDCi 310 L1 H1 is a versatile medium-sized panel van that combines strength, practicality, and comfort. Powered by a responsive 2.0-litre diesel engine, it delivers dependable performance and efficiency, ideal for both city work and longer motorway journeys. With the L1 short wheelbase and H1 standard roof design, it offers generous load capacity without compromising manoeuvrability. Inside, the cabin is smart and functional, with car-like comfort and useful technology to support your business every day.`,
    image: "images/ford-transit.jpg",
    year: 2017,
    mileage: 72589,
    fuelType: "Diesel",
    gearbox: "Manual",
    engineSize: "2.0L",
    color: "White",
    seats: 3,
    emissions: `157 g/km`,
    horsepower: "104 BHP",
    milesPerGallon: "46.3 MPG",
    euroStatus: "Euro 6",
    bodyType: "Panel Van",
    wheelbase: "SWB",
    id: 6,
    topSpeed: "100 mph",
    zeroToSixty: "12 secs",
    power: "104 bhp",
    height: "2,020mm",
    length: "4,972mm",
    width: "1,986mm",
    extraUrban: "0 mpg",
    urban: "0 mpg",
    imageSlides: [
      "images/ford-transit.jpg",
      "images/ford-transit1.jpg",
      "images/ford-transit2.jpg",
      "images/ford-transit3.jpg",
      "images/ford-transit4.jpg",
      "images/ford-transit5.jpg",
    ],
  },

  {
    name: "Toyota ProAce Icon Medium Panel Van MWB Euro 6 (s/s) 6dr",
    make: "Toyota",
    model: "ProAce",
    price: 5994,
    description: `The 2019 Toyota ProAce Icon 2.0 is a durable and spacious panel van geared for demanding workdays. Equipped with a 2.0L Euro 6 diesel engine delivering around 120 bhp and smooth manual shifting, it blends performance with economy for both urban and long-haul operations. With a medium-length body and standard roof, the Icon trim pairs comfort and essentials with excellent load capacity and Toyota’s renowned reliability.`,
    image: "images/toyota-proace.jpg",
    year: 2019,
    mileage: 136343,
    fuelType: "Diesel",
    gearbox: "Manual",
    engineSize: "2.0L",
    color: "White",
    seats: 3,
    emissions: "139 g/km",
    horsepower: "120 BHP",
    milesPerGallon: "53.3 MPG",
    euroStatus: "Euro 6",
    bodyType: "Panel Van",
    wheelbase: "MWB",
    id: 7,
    topSpeed: "105 mph",
    zeroToSixty: "13.3 secs",
    power: "120 bhp",
    height: "1,940 mm",
    length: "5,309 mm",
    width: "1,920 mm",
    extraUrban: "57.6 mpg",
    urban: "47.9 mpg",
    imageSlides: [
      "images/toyota-proace.jpg",
      "images/toyota-proace1.jpg",
      "images/toyota-proace2.jpg",
      "images/toyota-proace3.jpg",
      "images/toyota-proace4.jpg",
      "images/toyota-proace5.jpg",
    ],
  },
];

